### ISSUE TITLE
兄弟, 本地环境配置好之后, 页面报错.

### ISSUE THREAD

**Issue by Houtx** [liuzhenghang/Trojan-WebUI#3]
首页空白, 然后页面报错, 看不到登录注册页面.
![image](https://user-images.githubusercontent.com/17922172/81459609-80029000-91d3-11ea-9768-e050b9ea390a.png)

**Comment by Houtx** [comment]
@liuzhenghang

**Comment by liuzhenghang** [comment]
你留个联系方式  一会儿我联系你

**Comment by liuzhenghang** [comment]
这是安装的那个版本的？

**Comment by Houtx** [comment]
直接fork的你的代码https://github.com/liuzhenghang/Trojan-WebUI.
尝试了一下 始终出不来用户登录页面.

**Comment by Houtx** [comment]
@liuzhenghang

**Comment by Houtx** [comment]
是不是首次部署, 需要往数据库造点数据 @liuzhenghang

**Comment by Memory331** [comment]
> 是不是首次部署，需要往数据库造点数据@liuzhenghang

数据库导入了没

**Comment by liuzhenghang** [comment]
用最新3.1的release  里边有个说明

**Comment by Houtx** [comment]
> > 是不是首次部署，需要往数据库造点数据@liuzhenghang
> 
> 数据库导入了没

数据库导入了

**Comment by Houtx** [comment]
> 用最新3.1的release 里边有个说明

好的 我试一下

**Comment by Houtx** [comment]
@liuzhenghang 兄弟, 管理员root用户 默认密码是什么

**Comment by liuzhenghang** [comment]
也是root

**Comment by liuzhenghang** [comment]
或者是rootroot123。。。

**Comment by liuzhenghang** [comment]
可以了么

**Comment by Houtx** [comment]
可以了
