### ISSUE TITLE
使用3.1版本后续使用3.2增量包更新后无法使用

### ISSUE THREAD

**Issue by yukigod17** [liuzhenghang/Trojan-WebUI#5]
3.1的完整包直接方式webapps文件夹后可以正常使用并打开，但是使用3.2增量包把ROOT文件夹覆盖后，重启tomcat后，无法使用普通账户登录，后台登陆正常，如图，使用的tomcat9和sql5.6
![image](https://user-images.githubusercontent.com/33057399/82752999-c8859480-9df4-11ea-90b9-81a5f780b260.png)

**Comment by liuzhenghang** [comment]
清楚一下浏览器缓存试试

**Comment by liuzhenghang** [comment]
可以留一个联系方式否

**Comment by yukigod17** [comment]
已尝试清楚浏览器缓存也还是不行，https://t.me/kenistonleung

**Comment by liuzhenghang** [comment]
我在群里艾特你了
